import type {
  Control,
  EvidenceItem,
  SamaUpdate,
  Task,
  KpiData,
  WorkflowCounts,
  BoardItem,
  Notification,
} from "@/types";

// ─── KPI ────────────────────────────────────────────────────────
export const kpiData: KpiData = {
  readinessScore: 742,
  readinessDelta: 38,
  openGaps: 33,
  highGaps: 12,
  pendingEvidence: 18,
  overdueEvidence: 6,
  daysToReview: 14,
  reviewQuarter: "Q2 2026",
};

// ─── WORKFLOW ────────────────────────────────────────────────────
export const workflowCounts: WorkflowCounts = {
  assigned: 18,
  inReview: 13,
  approved: 8,
  evidenced: 34,
  overdue: 6,
  total: 79,
};

// ─── CONTROLS ────────────────────────────────────────────────────
export const controls: Control[] = [
  {
    id: "ctrl-001",
    name: "Access Control Review",
    domain: "IT Security · IAM Policy",
    risk: "high",
    evidenceStatus: "missing",
    workflowStatus: "overdue",
    owner: { initials: "IS", name: "IT Security Team", colorClass: "bg-[rgba(239,68,68,0.2)] text-risk-high" },
    deadline: "Mar 31, 2026",
    deadlineStatus: "overdue",
    description:
      "Periodic review of all IAM policies and user access rights to enforce least-privilege across banking systems and Azure resources. Required under SAMA CCSF Section 4.2.1.",
    samaRef: "SAMA CCSF 4.2.1",
  },
  {
    id: "ctrl-002",
    name: "Data Governance Framework",
    domain: "Data Governance · Compliance",
    risk: "high",
    evidenceStatus: "pending",
    workflowStatus: "in_review",
    owner: { initials: "DG", name: "Data Team", colorClass: "bg-[rgba(97,59,254,0.2)] text-[#A48DFF]" },
    deadline: "May 16, 2026",
    deadlineStatus: "soon",
    description:
      "Comprehensive data governance framework covering classification, lineage, ownership, and handling policies for all banking data assets aligned with SAMA data governance requirements.",
    samaRef: "SAMA DGF 2.1",
  },
  {
    id: "ctrl-003",
    name: "Encryption Standards Validation",
    domain: "Network Security · Cryptography",
    risk: "high",
    evidenceStatus: "review",
    workflowStatus: "in_review",
    owner: { initials: "NS", name: "Net Security", colorClass: "bg-[rgba(24,84,232,0.2)] text-[#6B9FFF]" },
    deadline: "May 19, 2026",
    deadlineStatus: "soon",
    description:
      "Validation of encryption standards across all data at-rest and in-transit scenarios. Covers AES-256 compliance, TLS 1.3 enforcement, and key management per SAMA CCSF.",
    samaRef: "SAMA CCSF 3.5",
  },
  {
    id: "ctrl-004",
    name: "Data Retention Policy",
    domain: "Compliance · SAMA Alignment",
    risk: "medium",
    evidenceStatus: "pending",
    workflowStatus: "assigned",
    owner: { initials: "CO", name: "Compliance Team", colorClass: "bg-[rgba(249,169,49,0.2)] text-risk-medium" },
    deadline: "May 24, 2026",
    deadlineStatus: "ok",
    description:
      "Formal data retention policy aligned with SAMA's data lifecycle management requirements. Covers retention periods, archival procedures, and secure disposal of expired financial data.",
    samaRef: "SAMA DLP 1.3",
  },
  {
    id: "ctrl-005",
    name: "Business Continuity & Resiliency",
    domain: "Infrastructure · DR Planning",
    risk: "medium",
    evidenceStatus: "approved",
    workflowStatus: "evidenced",
    owner: { initials: "IN", name: "Infrastructure", colorClass: "bg-[rgba(34,197,94,0.2)] text-risk-low" },
    deadline: "Jun 2, 2026",
    deadlineStatus: "ok",
    description:
      "Business continuity plan and disaster recovery procedures including RTO/RPO targets, failover testing results, and infrastructure resiliency validation per SAMA BCM framework.",
    samaRef: "SAMA BCM 2.0",
  },
  {
    id: "ctrl-006",
    name: "Audit Logging Standards",
    domain: "Compliance · SAMA",
    risk: "low",
    evidenceStatus: "approved",
    workflowStatus: "evidenced",
    owner: { initials: "CO", name: "Compliance Team", colorClass: "bg-[rgba(34,197,94,0.2)] text-risk-low" },
    deadline: "Jun 10, 2026",
    deadlineStatus: "ok",
    description:
      "Comprehensive audit logging configuration covering system events, user actions, and API calls. Logs retained for 12 months and accessible for audit review per SAMA requirements.",
    samaRef: "SAMA CCSF 4.4",
  },
  {
    id: "ctrl-007",
    name: "Privileged Access Management",
    domain: "IT Security · PAM",
    risk: "high",
    evidenceStatus: "pending",
    workflowStatus: "assigned",
    owner: { initials: "IS", name: "IT Security Team", colorClass: "bg-[rgba(239,68,68,0.2)] text-risk-high" },
    deadline: "May 28, 2026",
    deadlineStatus: "soon",
    description:
      "Implementation and validation of PAM controls for administrative accounts including session monitoring, just-in-time access provisioning, and privileged session recording.",
    samaRef: "SAMA PAM 1.1",
  },
  {
    id: "ctrl-008",
    name: "Third-Party Risk Assessment",
    domain: "Risk Management · Vendor",
    risk: "medium",
    evidenceStatus: "pending",
    workflowStatus: "assigned",
    owner: { initials: "RM", name: "Risk Management", colorClass: "bg-[rgba(249,169,49,0.2)] text-risk-medium" },
    deadline: "Jun 5, 2026",
    deadlineStatus: "ok",
    description:
      "Annual risk assessment of all third-party vendors with access to banking systems and customer data, covering due diligence, contract compliance, and security posture evaluation.",
    samaRef: "SAMA TPRM 3.0",
  },
  {
    id: "ctrl-009",
    name: "Network Segmentation Review",
    domain: "Network Security · Architecture",
    risk: "medium",
    evidenceStatus: "review",
    workflowStatus: "in_review",
    owner: { initials: "NS", name: "Net Security", colorClass: "bg-[rgba(24,84,232,0.2)] text-[#6B9FFF]" },
    deadline: "Jun 8, 2026",
    deadlineStatus: "ok",
    description:
      "Review of network segmentation controls to ensure proper isolation between core banking systems, DMZ, and internet-facing services in compliance with SAMA security architecture standards.",
  },
  {
    id: "ctrl-010",
    name: "Incident Response Procedures",
    domain: "Security Operations · IR",
    risk: "low",
    evidenceStatus: "approved",
    workflowStatus: "evidenced",
    owner: { initials: "SO", name: "SecOps Team", colorClass: "bg-[rgba(34,197,94,0.2)] text-risk-low" },
    deadline: "Jun 15, 2026",
    deadlineStatus: "ok",
    description:
      "Updated incident response procedures including the new 72-hour SAMA reporting obligation, escalation paths, stakeholder communication templates, and post-incident review process.",
    samaRef: "SAMA IR 2.1",
  },
];

// ─── EVIDENCE ────────────────────────────────────────────────────
export const evidenceItems: EvidenceItem[] = [
  {
    id: "ev-001",
    fileName: "IAM_Policy_Review_Q1_2026.pdf",
    controlId: "ctrl-001",
    controlName: "Access Control Review",
    stage: "review",
    submittedBy: { initials: "IS", name: "IT Security Team", colorClass: "bg-[rgba(239,68,68,0.2)] text-risk-high" },
    date: "May 8, 2026",
    fileSize: "2.4 MB",
    fileType: "PDF",
  },
  {
    id: "ev-002",
    fileName: "Data_Gov_Framework_v3.2.docx",
    controlId: "ctrl-002",
    controlName: "Data Governance Framework",
    stage: "pending",
    submittedBy: { initials: "DG", name: "Data Team", colorClass: "bg-[rgba(97,59,254,0.2)] text-[#A48DFF]" },
    date: "May 10, 2026",
    fileSize: "1.1 MB",
    fileType: "DOCX",
  },
  {
    id: "ev-003",
    fileName: "Encryption_Standards_Audit_Report.pdf",
    controlId: "ctrl-003",
    controlName: "Encryption Standards Validation",
    stage: "approved",
    submittedBy: { initials: "NS", name: "Net Security", colorClass: "bg-[rgba(24,84,232,0.2)] text-[#6B9FFF]" },
    date: "May 4, 2026",
    fileSize: "5.8 MB",
    fileType: "PDF",
  },
  {
    id: "ev-004",
    fileName: "BCP_DR_Test_Results_2026.xlsx",
    controlId: "ctrl-005",
    controlName: "Business Continuity & Resiliency",
    stage: "approved",
    submittedBy: { initials: "IN", name: "Infrastructure", colorClass: "bg-[rgba(34,197,94,0.2)] text-risk-low" },
    date: "Apr 28, 2026",
    fileSize: "890 KB",
    fileType: "XLSX",
  },
  {
    id: "ev-005",
    fileName: "Audit_Logging_Compliance_Check.json",
    controlId: "ctrl-006",
    controlName: "Audit Logging Standards",
    stage: "approved",
    submittedBy: { initials: "CO", name: "Compliance Team", colorClass: "bg-[rgba(34,197,94,0.2)] text-risk-low" },
    date: "Apr 20, 2026",
    fileSize: "320 KB",
    fileType: "JSON",
  },
  {
    id: "ev-006",
    fileName: "PAM_Implementation_Evidence.pdf",
    controlId: "ctrl-007",
    controlName: "Privileged Access Management",
    stage: "pending",
    submittedBy: { initials: "IS", name: "IT Security Team", colorClass: "bg-[rgba(239,68,68,0.2)] text-risk-high" },
    date: "May 11, 2026",
    fileSize: "3.1 MB",
    fileType: "PDF",
  },
  {
    id: "ev-007",
    fileName: "Network_Segmentation_Architecture.pdf",
    controlId: "ctrl-009",
    controlName: "Network Segmentation Review",
    stage: "review",
    submittedBy: { initials: "NS", name: "Net Security", colorClass: "bg-[rgba(24,84,232,0.2)] text-[#6B9FFF]" },
    date: "May 9, 2026",
    fileSize: "4.2 MB",
    fileType: "PDF",
  },
  {
    id: "ev-008",
    fileName: "IR_Procedures_Updated_2026.docx",
    controlId: "ctrl-010",
    controlName: "Incident Response Procedures",
    stage: "approved",
    submittedBy: { initials: "SO", name: "SecOps Team", colorClass: "bg-[rgba(34,197,94,0.2)] text-risk-low" },
    date: "Apr 15, 2026",
    fileSize: "780 KB",
    fileType: "DOCX",
  },
];

// ─── SAMA UPDATES ────────────────────────────────────────────────
export const samaUpdates: SamaUpdate[] = [
  {
    id: "sama-001",
    title: "Cloud Security Controls Update — SAMA CCSF 2.1",
    description:
      "Updated requirements for cloud data residency, access control segregation, and encryption key management for banking systems hosted on cloud platforms.",
    date: "May 6, 2026",
    type: "New Circular",
    status: "detected",
    impactedControls: 5,
    isNew: true,
  },
  {
    id: "sama-002",
    title: "Third-Party Risk Management Framework Update",
    description:
      "Enhanced due diligence requirements for all third-party vendors with access to banking systems or customer data, including annual re-assessment obligations.",
    date: "May 2, 2026",
    type: "Amendment",
    status: "detected",
    impactedControls: 4,
    isNew: true,
  },
  {
    id: "sama-003",
    title: "Cybersecurity Framework — Incident Reporting Revision",
    description:
      "New 72-hour mandatory incident reporting obligation for critical IT system events with structured SAMA notification procedures and escalation requirements.",
    date: "Apr 22, 2026",
    type: "Amendment",
    status: "mapped",
    impactedControls: 3,
  },
  {
    id: "sama-004",
    title: "Privileged Access Management Guidelines",
    description:
      "Mandatory PAM controls for administrative accounts including session monitoring, just-in-time provisioning, and privileged session recording requirements.",
    date: "Apr 14, 2026",
    type: "Guideline",
    status: "mapped",
    impactedControls: 6,
  },
  {
    id: "sama-005",
    title: "Open Banking API Standards — Data Governance",
    description:
      "Compliance framework for open banking APIs covering consent management, data portability, and audit logging requirements for API-exposed banking services.",
    date: "Apr 10, 2026",
    type: "Circular Update",
    status: "assigned",
    impactedControls: 7,
  },
  {
    id: "sama-006",
    title: "Financial Data Classification Policy",
    description:
      "Classification framework for financial customer data with tiered handling, storage, and transfer requirements based on sensitivity and regulatory exposure.",
    date: "Mar 28, 2026",
    type: "Policy",
    status: "assigned",
    impactedControls: 5,
  },
];

// ─── TASKS ────────────────────────────────────────────────────────
export const myTasks: Task[] = [
  {
    id: "task-001",
    title: "Review Access Control evidence submitted by IT Security",
    meta: "Evidence Validation · IT Security Team",
    priority: "high",
    due: "Overdue",
    deadlineStatus: "overdue",
  },
  {
    id: "task-002",
    title: "Approve Data Governance Framework document v3.2",
    meta: "Approval Required · Data Team",
    priority: "high",
    due: "4 days",
    deadlineStatus: "soon",
  },
  {
    id: "task-003",
    title: "Map new SAMA CCSF 2.1 circular to impacted controls",
    meta: "Regulatory Mapping · SAMA Update",
    priority: "medium",
    due: "7 days",
    deadlineStatus: "soon",
  },
  {
    id: "task-004",
    title: "Confirm audit evidence export scope for Q2 review",
    meta: "Audit Pack · Q2 External Audit",
    priority: "low",
    due: "14 days",
    deadlineStatus: "ok",
  },
];

// ─── KANBAN BOARD ITEMS ─────────────────────────────────────────
export const boardItems: BoardItem[] = [
  // ── OVERDUE ──
  {
    id: "b-ov-1",
    name: "Access Control Review",
    domain: "IT Security · IAM",
    risk: "high",
    owner: { initials: "IS", name: "IT Security", colorClass: "bg-[rgba(239,68,68,0.2)] text-risk-high" },
    deadline: "Mar 31, 2026",
    deadlineStatus: "overdue",
    workflowStatus: "overdue",
    samaRef: "CCSF 4.2.1",
    description: "Periodic review of all IAM policies and user access rights across core banking systems. Enforces least-privilege principles and removes stale permissions. Required under SAMA CCSF 4.2.1 — currently 44 days overdue and blocking two downstream controls.",
    requirements: [
      "Review all active user accounts and permission levels",
      "Remove stale, orphaned, and excessive access rights",
      "Validate service account privileges against principle of least privilege",
      "Generate signed access certification report for auditors",
    ],
    documents: [
      { name: "IAM_Policy_Review_Q1_2026.pdf", type: "PDF", size: "2.4 MB", date: "Apr 12, 2026", status: "review", uploadedBy: "IT Security" },
      { name: "Access_Rights_Matrix_v2.xlsx", type: "XLSX", size: "1.1 MB", date: "Apr 10, 2026", status: "pending", uploadedBy: "IT Security" },
      { name: "Azure_AD_User_Export.csv", type: "CSV", size: "340 KB", date: "Apr 12, 2026", status: "pending", uploadedBy: "IT Security" },
    ],
  },
  {
    id: "b-ov-2",
    name: "Password Policy Enforcement",
    domain: "IT Security · IAM",
    risk: "high",
    owner: { initials: "IS", name: "IT Security", colorClass: "bg-[rgba(239,68,68,0.2)] text-risk-high" },
    deadline: "Apr 15, 2026",
    deadlineStatus: "overdue",
    workflowStatus: "overdue",
    samaRef: "CCSF 4.1",
    description: "Validation that all system and user accounts comply with the bank's enforced password policy. Includes minimum complexity rules, 90-day rotation enforcement, and MFA activation verification. Now 29 days overdue.",
    requirements: [
      "Verify minimum 12-character password requirement is enforced",
      "Confirm 90-day password rotation policy is active on all accounts",
      "Validate MFA activation across all privileged and external-access accounts",
      "Produce and sign off on non-compliant account remediation report",
    ],
    documents: [
      { name: "Password_Policy_v2.3.pdf", type: "PDF", size: "850 KB", date: "Mar 10, 2026", status: "approved", uploadedBy: "IT Security" },
      { name: "Non_Compliant_Accounts_Report.xlsx", type: "XLSX", size: "220 KB", date: "—", status: "missing", uploadedBy: "—" },
      { name: "MFA_Activation_Status_Export.xlsx", type: "XLSX", size: "410 KB", date: "Apr 8, 2026", status: "pending", uploadedBy: "IT Security" },
    ],
  },
  {
    id: "b-ov-3",
    name: "Vendor Security Assessment",
    domain: "Risk Mgmt · Vendor",
    risk: "medium",
    owner: { initials: "RM", name: "Risk Mgmt", colorClass: "bg-[rgba(249,169,49,0.2)] text-risk-medium" },
    deadline: "Apr 30, 2026",
    deadlineStatus: "overdue",
    workflowStatus: "overdue",
    samaRef: "TPRM 3.0",
    description: "Annual security assessment of third-party vendors with access to banking systems and customer data. Evaluates their security posture, contract compliance, and incident response readiness under SAMA TPRM requirements.",
    requirements: [
      "Complete vendor security questionnaire for all Tier-1 vendors",
      "Review and validate vendor penetration test results from last 12 months",
      "Confirm cyber insurance coverage meets contractual minimums",
      "Update vendor risk register with new classification scores",
    ],
    documents: [
      { name: "Vendor_Risk_Register_2026.xlsx", type: "XLSX", size: "1.8 MB", date: "Mar 15, 2026", status: "pending", uploadedBy: "Risk Mgmt" },
      { name: "Vendor_Security_Questionnaire_Template.docx", type: "DOCX", size: "420 KB", date: "Feb 28, 2026", status: "approved", uploadedBy: "Risk Mgmt" },
      { name: "Vendor_Pentest_Summary_2025.pdf", type: "PDF", size: "2.1 MB", date: "—", status: "missing", uploadedBy: "—" },
    ],
  },
  // ── ASSIGNED ──
  {
    id: "b-as-1",
    name: "Data Retention Policy",
    domain: "Compliance · SAMA",
    risk: "medium",
    owner: { initials: "CO", name: "Compliance", colorClass: "bg-[rgba(249,169,49,0.2)] text-risk-medium" },
    deadline: "May 24, 2026",
    deadlineStatus: "soon",
    workflowStatus: "assigned",
    samaRef: "DLP 1.3",
    description: "Formal data retention policy aligned with SAMA's data lifecycle management requirements. Covers retention periods for all data classifications, archival procedures, and secure disposal of expired financial data per DLP 1.3.",
    requirements: [
      "Define retention periods for each data classification tier",
      "Implement automated archival triggers in the data platform",
      "Document and test secure data disposal procedures",
      "Obtain Legal and Compliance sign-off on the final retention schedule",
    ],
    documents: [
      { name: "Data_Retention_Policy_Draft_v1.2.docx", type: "DOCX", size: "640 KB", date: "May 5, 2026", status: "pending", uploadedBy: "Compliance" },
      { name: "Retention_Schedule_Matrix.xlsx", type: "XLSX", size: "380 KB", date: "May 8, 2026", status: "pending", uploadedBy: "Compliance" },
    ],
  },
  {
    id: "b-as-2",
    name: "Privileged Access Management",
    domain: "IT Security · PAM",
    risk: "high",
    owner: { initials: "IS", name: "IT Security", colorClass: "bg-[rgba(239,68,68,0.2)] text-risk-high" },
    deadline: "May 28, 2026",
    deadlineStatus: "soon",
    workflowStatus: "assigned",
    samaRef: "PAM 1.1",
    description: "Implementation and validation of PAM controls for all administrative accounts, including session monitoring, just-in-time access provisioning, and privileged session recording. Mandatory under SAMA PAM 1.1.",
    requirements: [
      "Deploy PAM solution and onboard all admin and service accounts",
      "Configure session recording for all privileged remote sessions",
      "Implement JIT access provisioning workflow with approval gate",
      "Conduct and document quarterly PAM access review",
    ],
    documents: [
      { name: "PAM_Implementation_Plan.pdf", type: "PDF", size: "1.2 MB", date: "May 10, 2026", status: "pending", uploadedBy: "IT Security" },
      { name: "Privileged_Account_Inventory.xlsx", type: "XLSX", size: "290 KB", date: "May 9, 2026", status: "pending", uploadedBy: "IT Security" },
    ],
  },
  {
    id: "b-as-3",
    name: "Third-Party Risk Assessment",
    domain: "Risk Mgmt · Vendor",
    risk: "medium",
    owner: { initials: "RM", name: "Risk Mgmt", colorClass: "bg-[rgba(249,169,49,0.2)] text-risk-medium" },
    deadline: "Jun 5, 2026",
    deadlineStatus: "ok",
    workflowStatus: "assigned",
    samaRef: "TPRM 3.0",
    description: "Annual risk assessment covering all third-party vendors with access to banking systems and customer data. Includes due diligence reviews, SOC 2 report validation, and contract compliance checks under the updated SAMA TPRM framework.",
    requirements: [
      "Identify and classify all Tier-1 and Tier-2 vendors by risk level",
      "Distribute and collect vendor security assessment questionnaires",
      "Review SOC 2 Type II or equivalent reports for critical vendors",
      "Update the vendor risk classification and approval register",
    ],
    documents: [
      { name: "Vendor_List_Q2_2026.xlsx", type: "XLSX", size: "560 KB", date: "May 7, 2026", status: "pending", uploadedBy: "Risk Mgmt" },
      { name: "TPRM_Assessment_Template.docx", type: "DOCX", size: "330 KB", date: "Apr 20, 2026", status: "approved", uploadedBy: "Risk Mgmt" },
    ],
  },
  {
    id: "b-as-4",
    name: "Cloud Security Baseline",
    domain: "IT Security · Cloud",
    risk: "high",
    owner: { initials: "IS", name: "IT Security", colorClass: "bg-[rgba(239,68,68,0.2)] text-risk-high" },
    deadline: "Jun 1, 2026",
    deadlineStatus: "ok",
    workflowStatus: "assigned",
    samaRef: "CCSF 2.1",
    description: "Security baseline assessment for all cloud-hosted banking services on Azure. Validates CIS benchmark compliance, resource group permissions, encryption at rest, and network security group policies per SAMA CCSF 2.1.",
    requirements: [
      "Run and document CIS Azure Security Benchmark assessment",
      "Validate AES-256 encryption is enabled on all storage accounts and databases",
      "Review all network security group rules for unnecessary exposure",
      "Confirm private endpoint configuration for all PaaS services",
    ],
    documents: [
      { name: "Azure_Security_Baseline_Report.pdf", type: "PDF", size: "3.1 MB", date: "May 11, 2026", status: "pending", uploadedBy: "IT Security" },
      { name: "Cloud_Resource_Inventory.xlsx", type: "XLSX", size: "720 KB", date: "May 10, 2026", status: "pending", uploadedBy: "IT Security" },
      { name: "CIS_Benchmark_Scan_Results.pdf", type: "PDF", size: "1.9 MB", date: "—", status: "missing", uploadedBy: "—" },
    ],
  },
  {
    id: "b-as-5",
    name: "API Security Review",
    domain: "Network · Open Banking",
    risk: "medium",
    owner: { initials: "NS", name: "Net Security", colorClass: "bg-[rgba(24,84,232,0.2)] text-[#6B9FFF]" },
    deadline: "Jun 7, 2026",
    deadlineStatus: "ok",
    workflowStatus: "assigned",
    description: "Security review of all open banking API endpoints covering authentication, authorization, rate limiting, and data leakage controls. Aligned with SAMA Open Banking API Standards and OWASP API Security Top 10.",
    requirements: [
      "Audit all public-facing API endpoints and document their authentication method",
      "Validate OAuth 2.0 and OpenID Connect implementation across all services",
      "Test rate limiting, throttle controls, and payload size restrictions",
      "Verify API access logs are retained for a minimum of 12 months",
    ],
    documents: [
      { name: "API_Security_Checklist.docx", type: "DOCX", size: "210 KB", date: "May 12, 2026", status: "pending", uploadedBy: "Net Security" },
      { name: "OpenBanking_API_Inventory.xlsx", type: "XLSX", size: "450 KB", date: "May 6, 2026", status: "pending", uploadedBy: "Net Security" },
    ],
  },
  // ── IN REVIEW ──
  {
    id: "b-ir-1",
    name: "Data Governance Framework",
    domain: "Data Governance",
    risk: "high",
    owner: { initials: "DG", name: "Data Team", colorClass: "bg-[rgba(97,59,254,0.2)] text-[#A48DFF]" },
    deadline: "May 16, 2026",
    deadlineStatus: "soon",
    workflowStatus: "in_review",
    samaRef: "DGF 2.1",
    description: "Comprehensive data governance framework covering classification, data lineage, ownership assignments, and handling policies for all banking data assets. Currently under active review by the Data Team and Compliance — due in 2 days.",
    requirements: [
      "Publish data classification taxonomy across all 4 sensitivity tiers",
      "Assign named data owners for all critical and confidential datasets",
      "Establish data lineage tracking process using the approved tool",
      "Define and document cross-border data transfer controls",
    ],
    documents: [
      { name: "Data_Gov_Framework_v3.2.docx", type: "DOCX", size: "1.1 MB", date: "May 10, 2026", status: "review", uploadedBy: "Data Team" },
      { name: "Data_Classification_Matrix.xlsx", type: "XLSX", size: "670 KB", date: "May 9, 2026", status: "review", uploadedBy: "Data Team" },
      { name: "Data_Owner_Registry.pdf", type: "PDF", size: "440 KB", date: "May 8, 2026", status: "pending", uploadedBy: "Data Team" },
    ],
  },
  {
    id: "b-ir-2",
    name: "Encryption Standards Validation",
    domain: "Network · Cryptography",
    risk: "high",
    owner: { initials: "NS", name: "Net Security", colorClass: "bg-[rgba(24,84,232,0.2)] text-[#6B9FFF]" },
    deadline: "May 19, 2026",
    deadlineStatus: "soon",
    workflowStatus: "in_review",
    samaRef: "CCSF 3.5",
    description: "Validation of encryption standards across all data-at-rest and data-in-transit scenarios. Covers AES-256 compliance, TLS 1.3 enforcement on all external endpoints, and key management procedures per SAMA CCSF 3.5.",
    requirements: [
      "Validate AES-256 encryption is applied to all database and file storage tiers",
      "Confirm TLS 1.3 is enforced on all external-facing APIs and endpoints",
      "Review key rotation procedures — confirm rotation occurs every 90 days",
      "Test and document data-in-transit encryption on all internal service calls",
    ],
    documents: [
      { name: "Encryption_Standards_Audit_Report.pdf", type: "PDF", size: "5.8 MB", date: "May 4, 2026", status: "review", uploadedBy: "Net Security" },
      { name: "TLS_Certificate_Inventory.xlsx", type: "XLSX", size: "310 KB", date: "May 6, 2026", status: "review", uploadedBy: "Net Security" },
      { name: "Key_Management_Policy_v1.1.pdf", type: "PDF", size: "780 KB", date: "Apr 28, 2026", status: "approved", uploadedBy: "Net Security" },
    ],
  },
  {
    id: "b-ir-3",
    name: "Network Segmentation Review",
    domain: "Network · Architecture",
    risk: "medium",
    owner: { initials: "NS", name: "Net Security", colorClass: "bg-[rgba(24,84,232,0.2)] text-[#6B9FFF]" },
    deadline: "Jun 8, 2026",
    deadlineStatus: "ok",
    workflowStatus: "in_review",
    description: "Review of network segmentation controls to ensure proper isolation between core banking systems, DMZ, and internet-facing services. Validates firewall rule hygiene and VLAN configuration in compliance with SAMA security architecture standards.",
    requirements: [
      "Map all current network zones, trust boundaries, and segment ownership",
      "Validate firewall rules between each network segment for excess permissions",
      "Confirm no lateral movement pathways between PCI-DSS zones",
      "Document VLAN segmentation configuration and obtain network team sign-off",
    ],
    documents: [
      { name: "Network_Segmentation_Diagram.pdf", type: "PDF", size: "2.2 MB", date: "May 7, 2026", status: "review", uploadedBy: "Net Security" },
      { name: "Firewall_Rules_Audit.xlsx", type: "XLSX", size: "890 KB", date: "May 5, 2026", status: "review", uploadedBy: "Net Security" },
      { name: "VLAN_Config_Export.txt", type: "TXT", size: "125 KB", date: "May 6, 2026", status: "pending", uploadedBy: "Net Security" },
    ],
  },
  {
    id: "b-ir-4",
    name: "User Authentication Controls",
    domain: "IT Security · MFA",
    risk: "high",
    owner: { initials: "IS", name: "IT Security", colorClass: "bg-[rgba(239,68,68,0.2)] text-risk-high" },
    deadline: "May 22, 2026",
    deadlineStatus: "soon",
    workflowStatus: "in_review",
    samaRef: "CCSF 4.3",
    description: "Assessment of authentication controls across all banking applications including MFA enforcement rates, SSO configuration with Azure AD, and session timeout policy compliance. Evidence under review ahead of the May 22 deadline.",
    requirements: [
      "Confirm MFA is enabled and enforced for 100% of user accounts",
      "Validate SSO integration is operational with Azure Active Directory",
      "Review and confirm session timeout thresholds meet the 15-minute policy",
      "Audit failed login attempt alerting and account lockout configuration",
    ],
    documents: [
      { name: "MFA_Adoption_Report_Q1_2026.pdf", type: "PDF", size: "1.4 MB", date: "May 9, 2026", status: "review", uploadedBy: "IT Security" },
      { name: "Authentication_Config_Audit.xlsx", type: "XLSX", size: "530 KB", date: "May 8, 2026", status: "review", uploadedBy: "IT Security" },
      { name: "SSO_Integration_Architecture.pdf", type: "PDF", size: "660 KB", date: "May 7, 2026", status: "pending", uploadedBy: "IT Security" },
    ],
  },
  // ── APPROVED ──
  {
    id: "b-ap-1",
    name: "Audit Logging Standards",
    domain: "Compliance · SAMA",
    risk: "low",
    owner: { initials: "CO", name: "Compliance", colorClass: "bg-[rgba(34,197,94,0.2)] text-risk-low" },
    deadline: "Jun 10, 2026",
    deadlineStatus: "ok",
    workflowStatus: "approved",
    samaRef: "CCSF 4.4",
    description: "Comprehensive audit logging configuration covering system events, user actions, and API calls across all tier-1 banking platforms. Logs retained for 12 months in tamper-proof storage with SIEM integration. All evidence approved — awaiting final evidencing.",
    requirements: [
      "Configure structured logging on all tier-1 and tier-2 production systems",
      "Enable centralised log forwarding to SIEM with alerting",
      "Set and validate 12-month log retention with tamper-proof write-once storage",
      "Validate log integrity checksums on a quarterly basis",
    ],
    documents: [
      { name: "Audit_Logging_Policy_v2.0.pdf", type: "PDF", size: "1.0 MB", date: "Apr 20, 2026", status: "approved", uploadedBy: "Compliance" },
      { name: "SIEM_Log_Coverage_Report.xlsx", type: "XLSX", size: "760 KB", date: "Apr 25, 2026", status: "approved", uploadedBy: "Compliance" },
      { name: "Log_Retention_Configuration.pdf", type: "PDF", size: "320 KB", date: "Apr 22, 2026", status: "approved", uploadedBy: "SecOps" },
    ],
  },
  {
    id: "b-ap-2",
    name: "Incident Response Procedures",
    domain: "SecOps · IR",
    risk: "low",
    owner: { initials: "SO", name: "SecOps", colorClass: "bg-[rgba(34,197,94,0.2)] text-risk-low" },
    deadline: "Jun 15, 2026",
    deadlineStatus: "ok",
    workflowStatus: "approved",
    samaRef: "IR 2.1",
    description: "Updated incident response procedures aligned with SAMA's 72-hour reporting obligation. Includes escalation paths, P1/P2/P3 classification guide, stakeholder communication templates, and post-incident review process. All documentation fully approved.",
    requirements: [
      "Define and document P1/P2/P3 incident severity classification criteria",
      "Document the 72-hour SAMA notification workflow with contact list",
      "Assign incident response roles, deputies, and escalation contacts",
      "Conduct and log a quarterly IR tabletop exercise with results",
    ],
    documents: [
      { name: "Incident_Response_Plan_v3.1.pdf", type: "PDF", size: "2.8 MB", date: "Apr 18, 2026", status: "approved", uploadedBy: "SecOps" },
      { name: "IR_Escalation_Matrix.xlsx", type: "XLSX", size: "210 KB", date: "Apr 17, 2026", status: "approved", uploadedBy: "SecOps" },
      { name: "SAMA_72h_Notification_Template.docx", type: "DOCX", size: "145 KB", date: "Apr 16, 2026", status: "approved", uploadedBy: "Compliance" },
    ],
  },
  {
    id: "b-ap-3",
    name: "Vulnerability Scanning Policy",
    domain: "IT Security · VAPT",
    risk: "medium",
    owner: { initials: "IS", name: "IT Security", colorClass: "bg-[rgba(239,68,68,0.2)] text-risk-high" },
    deadline: "Jun 12, 2026",
    deadlineStatus: "ok",
    workflowStatus: "approved",
    samaRef: "CCSF 5.1",
    description: "Policy and procedures for regular vulnerability scanning of all production systems. Defines scan frequency, CVSS severity thresholds, mandatory patching SLAs, and automated reporting requirements per SAMA CCSF 5.1. Evidence approved.",
    requirements: [
      "Define scan frequency: weekly for critical assets, monthly for all others",
      "Set CVSS ≥7.0 as the mandatory patching threshold within 72 hours",
      "Establish 30-day remediation SLA for high-severity CVEs",
      "Configure automated scan reports delivered to CISO and risk team",
    ],
    documents: [
      { name: "Vulnerability_Scanning_Policy_v1.4.pdf", type: "PDF", size: "1.6 MB", date: "Apr 24, 2026", status: "approved", uploadedBy: "IT Security" },
      { name: "Q1_2026_Scan_Results_Summary.xlsx", type: "XLSX", size: "1.2 MB", date: "Apr 22, 2026", status: "approved", uploadedBy: "IT Security" },
      { name: "Critical_CVE_Remediation_Log.pdf", type: "PDF", size: "540 KB", date: "Apr 28, 2026", status: "approved", uploadedBy: "IT Security" },
    ],
  },
  // ── EVIDENCED ──
  {
    id: "b-ev-1",
    name: "Business Continuity & Resiliency",
    domain: "Infrastructure · DR",
    risk: "medium",
    owner: { initials: "IN", name: "Infrastructure", colorClass: "bg-[rgba(34,197,94,0.2)] text-risk-low" },
    deadline: "Jun 2, 2026",
    deadlineStatus: "ok",
    workflowStatus: "evidenced",
    samaRef: "BCM 2.0",
    description: "Business continuity plan and disaster recovery procedures fully evidenced, including validated RTO ≤4h / RPO ≤1h targets, DR failover test results, and backup site readiness sign-off. Fully compliant with SAMA BCM 2.0.",
    requirements: [
      "Document and validate RTO ≤4h and RPO ≤1h for all tier-1 systems",
      "Conduct and record the annual DR failover test with pass/fail outcome",
      "Validate backup site infrastructure readiness and capacity",
      "Obtain business stakeholder sign-off on the BCP document",
    ],
    documents: [
      { name: "BCP_Document_v4.0.pdf", type: "PDF", size: "4.2 MB", date: "Apr 2, 2026", status: "approved", uploadedBy: "Infrastructure" },
      { name: "DR_Failover_Test_Results_Q1_2026.xlsx", type: "XLSX", size: "890 KB", date: "Apr 5, 2026", status: "approved", uploadedBy: "Infrastructure" },
      { name: "RTO_RPO_Validation_Report.pdf", type: "PDF", size: "1.1 MB", date: "Apr 8, 2026", status: "approved", uploadedBy: "Infrastructure" },
    ],
  },
  {
    id: "b-ev-2",
    name: "Change Management Process",
    domain: "IT Operations · ITSM",
    risk: "low",
    owner: { initials: "IO", name: "IT Ops", colorClass: "bg-[rgba(97,59,254,0.2)] text-[#A48DFF]" },
    deadline: "Jun 18, 2026",
    deadlineStatus: "ok",
    workflowStatus: "evidenced",
    description: "Formal change management process for all production system modifications including CAB approval workflow, mandatory rollback plans for high-risk changes, and emergency change handling procedures. Fully documented and evidenced.",
    requirements: [
      "All standard changes must pass through CAB approval before deployment",
      "Rollback plans are mandatory for any change classified as high-risk",
      "All changes must be logged in the ITSM platform with completion confirmation",
      "Emergency change procedure must be followed for out-of-band deployments",
    ],
    documents: [
      { name: "Change_Management_Process_v2.2.pdf", type: "PDF", size: "1.8 MB", date: "Mar 20, 2026", status: "approved", uploadedBy: "IT Ops" },
      { name: "CAB_Meeting_Minutes_Q1_2026.pdf", type: "PDF", size: "560 KB", date: "Mar 31, 2026", status: "approved", uploadedBy: "IT Ops" },
      { name: "Change_Log_Q1_2026.xlsx", type: "XLSX", size: "730 KB", date: "Mar 31, 2026", status: "approved", uploadedBy: "IT Ops" },
    ],
  },
  {
    id: "b-ev-3",
    name: "Asset Inventory Management",
    domain: "IT Operations · CMDB",
    risk: "low",
    owner: { initials: "IO", name: "IT Ops", colorClass: "bg-[rgba(97,59,254,0.2)] text-[#A48DFF]" },
    deadline: "Jun 20, 2026",
    deadlineStatus: "ok",
    workflowStatus: "evidenced",
    description: "Complete hardware and software asset inventory maintained through the CMDB. Covers all servers, endpoints, network devices, and SaaS licenses. Quarterly reconciliation process in place and evidenced for SAMA audit requirements.",
    requirements: [
      "Maintain CMDB with complete hardware asset records and ownership",
      "Track all software licenses, versions, and expiry dates",
      "Conduct and document quarterly asset reconciliation against CMDB",
      "Flag and initiate secure disposal workflow for decommissioned assets",
    ],
    documents: [
      { name: "Asset_Inventory_Q1_2026.xlsx", type: "XLSX", size: "2.1 MB", date: "Mar 28, 2026", status: "approved", uploadedBy: "IT Ops" },
      { name: "CMDB_Snapshot_May_2026.pdf", type: "PDF", size: "1.4 MB", date: "May 1, 2026", status: "approved", uploadedBy: "IT Ops" },
      { name: "Software_License_Register.xlsx", type: "XLSX", size: "830 KB", date: "Mar 31, 2026", status: "approved", uploadedBy: "IT Ops" },
    ],
  },
  {
    id: "b-ev-4",
    name: "System Backup Procedures",
    domain: "Infrastructure · Recovery",
    risk: "low",
    owner: { initials: "IN", name: "Infrastructure", colorClass: "bg-[rgba(34,197,94,0.2)] text-risk-low" },
    deadline: "Jun 22, 2026",
    deadlineStatus: "ok",
    workflowStatus: "evidenced",
    samaRef: "BCM 1.2",
    description: "Documented backup procedures for all critical banking systems including backup frequency per system tier, storage locations, AES-256 encryption at rest, and quarterly restoration test results. Aligned with SAMA BCM 1.2.",
    requirements: [
      "Define and document backup frequency for each system tier (daily/hourly)",
      "Ensure all backup archives are encrypted with AES-256 at rest",
      "Perform and record quarterly restoration tests for critical systems",
      "Maintain geographically separated offsite backup copies",
    ],
    documents: [
      { name: "Backup_Procedures_v2.1.pdf", type: "PDF", size: "1.3 MB", date: "Apr 10, 2026", status: "approved", uploadedBy: "Infrastructure" },
      { name: "Backup_Restoration_Test_Q1_2026.xlsx", type: "XLSX", size: "480 KB", date: "Apr 15, 2026", status: "approved", uploadedBy: "Infrastructure" },
      { name: "Backup_Schedule_All_Systems.xlsx", type: "XLSX", size: "310 KB", date: "Mar 30, 2026", status: "approved", uploadedBy: "Infrastructure" },
    ],
  },
  {
    id: "b-ev-5",
    name: "Security Awareness Training",
    domain: "HR · People Security",
    risk: "low",
    owner: { initials: "HR", name: "HR Dept", colorClass: "bg-[rgba(97,59,254,0.2)] text-[#A48DFF]" },
    deadline: "Jun 25, 2026",
    deadlineStatus: "ok",
    workflowStatus: "evidenced",
    description: "Annual mandatory security awareness training completed by all 412 staff members. Covers phishing recognition, password hygiene, data classification handling, and SAMA compliance obligations. Training records and completion certificates fully evidenced.",
    requirements: [
      "Achieve 100% staff training completion as tracked in the LMS",
      "Include and record a phishing simulation exercise with click-rate metrics",
      "Export completion report from LMS signed off by HR",
      "Collect and archive individual staff acknowledgement sign-offs",
    ],
    documents: [
      { name: "Security_Training_Completion_Report.pdf", type: "PDF", size: "920 KB", date: "Mar 15, 2026", status: "approved", uploadedBy: "HR Dept" },
      { name: "Phishing_Simulation_Results_Q1_2026.xlsx", type: "XLSX", size: "340 KB", date: "Mar 18, 2026", status: "approved", uploadedBy: "HR Dept" },
      { name: "Staff_Acknowledgement_Log.pdf", type: "PDF", size: "1.7 MB", date: "Mar 20, 2026", status: "approved", uploadedBy: "HR Dept" },
    ],
  },
];

// ─── NOTIFICATIONS ──────────────────────────────────────────────
export const notifications: Notification[] = [
  // Unread — high priority
  {
    id: "notif-001",
    type: "sama",
    title: "New SAMA Circular Detected",
    description: "Cloud Security Controls Update (SAMA CCSF 2.1) has been published. 5 controls in your register are potentially impacted and require immediate mapping.",
    timestamp: "2026-05-13T08:14:00",
    timeAgo: "2 hours ago",
    read: false,
    priority: "high",
    actionLabel: "Map Controls",
    actionHref: "/regulations",
    meta: "SAMA CCSF 2.1 · New Circular",
  },
  {
    id: "notif-002",
    type: "sama",
    title: "Third-Party Risk Framework Amendment",
    description: "SAMA has amended the Third-Party Risk Management Framework, introducing enhanced due diligence requirements for all vendors with access to banking systems.",
    timestamp: "2026-05-12T16:45:00",
    timeAgo: "17 hours ago",
    read: false,
    priority: "high",
    actionLabel: "Review Update",
    actionHref: "/regulations",
    meta: "SAMA TPRM · Amendment",
  },
  {
    id: "notif-003",
    type: "evidence",
    title: "Evidence Overdue — Access Control Review",
    description: "IAM Policy Review evidence for ctrl-001 was due on Mar 31, 2026 and has not been submitted. This control is now flagged as overdue in your governance board.",
    timestamp: "2026-05-13T07:00:00",
    timeAgo: "3 hours ago",
    read: false,
    priority: "high",
    actionLabel: "View Control",
    actionHref: "/controls",
    meta: "ctrl-001 · IT Security · Overdue",
  },
  {
    id: "notif-004",
    type: "approval",
    title: "Evidence Awaiting Your Approval",
    description: "IAM Policy Review Q1 2026 (PDF, 2.4 MB) has been submitted by IT Security Team and is pending your review and approval before it can be marked as evidenced.",
    timestamp: "2026-05-12T14:22:00",
    timeAgo: "19 hours ago",
    read: false,
    priority: "medium",
    actionLabel: "Review & Approve",
    actionHref: "/governance",
    meta: "IT Security Team · Evidence Approval",
  },
  {
    id: "notif-005",
    type: "task",
    title: "Task Assigned — SAMA Circular Mapping",
    description: "You have been assigned to map the new SAMA CCSF 2.1 circular to impacted controls in the register. Target completion: May 20, 2026.",
    timestamp: "2026-05-13T08:30:00",
    timeAgo: "1 hour ago",
    read: false,
    priority: "medium",
    actionLabel: "Start Task",
    actionHref: "/governance",
    meta: "Assigned by · Compliance Team",
  },
  // Read notifications
  {
    id: "notif-006",
    type: "approval",
    title: "Evidence Approved — Audit Logging Standards",
    description: "Logging Compliance Check v2 submitted by the Compliance Team has been approved. Control ctrl-006 is now marked as Evidenced in the governance board.",
    timestamp: "2026-05-11T11:05:00",
    timeAgo: "2 days ago",
    read: true,
    priority: "low",
    actionLabel: "View Control",
    actionHref: "/controls",
    meta: "ctrl-006 · Compliance Team",
  },
  {
    id: "notif-007",
    type: "evidence",
    title: "Evidence Submitted for Review",
    description: "Data Governance Framework v3.2 (DOCX, 1.1 MB) has been submitted by the Data Team for review. Please review and approve within 5 business days.",
    timestamp: "2026-05-10T09:30:00",
    timeAgo: "3 days ago",
    read: true,
    priority: "medium",
    actionLabel: "View Evidence",
    actionHref: "/evidence",
    meta: "Data Team · ctrl-002",
  },
  {
    id: "notif-008",
    type: "system",
    title: "Readiness Score Improved",
    description: "Your governance readiness score has increased by +38 points to 742/1000 following the approval of three new evidence items. Keep up the momentum.",
    timestamp: "2026-05-09T17:00:00",
    timeAgo: "4 days ago",
    read: true,
    priority: "low",
    actionLabel: "View Dashboard",
    actionHref: "/dashboard",
    meta: "Score: 742 / 1000 · +38 this period",
  },
  {
    id: "notif-009",
    type: "task",
    title: "Task Completed — Incident Response Procedures",
    description: "The Incident Response Procedures evidence has been submitted, reviewed, and approved. ctrl-010 is now fully evidenced ahead of the Q2 2026 audit cycle.",
    timestamp: "2026-05-08T15:20:00",
    timeAgo: "5 days ago",
    read: true,
    priority: "low",
    actionHref: "/controls",
    meta: "SecOps Team · ctrl-010",
  },
  {
    id: "notif-010",
    type: "system",
    title: "Q2 2026 Audit Cycle — 14 Days Remaining",
    description: "The Q2 2026 external audit review is scheduled in 14 days. You currently have 18 pending evidence items and 6 overdue controls. Prioritise your action list.",
    timestamp: "2026-05-07T08:00:00",
    timeAgo: "6 days ago",
    read: true,
    priority: "medium",
    actionLabel: "View Dashboard",
    actionHref: "/dashboard",
    meta: "Q2 2026 · External Audit",
  },
];

export const approvalQueue: Task[] = [
  {
    id: "apq-001",
    title: "Encryption_Audit_2026.pdf submitted by Net Sec",
    meta: "Evidence Approval · Encryption Standards",
    priority: "medium",
    due: "Pending",
    deadlineStatus: "soon",
  },
  {
    id: "apq-002",
    title: "IAM Policy Review Q1 submitted by IT Security",
    meta: "Evidence Approval · Access Control",
    priority: "high",
    due: "Pending",
    deadlineStatus: "soon",
  },
  {
    id: "apq-003",
    title: "Logging Compliance Check v2 approved by Compliance",
    meta: "Final Approval · Audit Logging",
    priority: "low",
    due: "Done",
    deadlineStatus: "ok",
  },
];
