import type {
  Control,
  EvidenceItem,
  SamaUpdate,
  Task,
  KpiData,
  WorkflowCounts,
  BoardItem,
  Notification,
} from "@/types";

// ─── KPI ────────────────────────────────────────────────────────
export const kpiData: KpiData = {
  readinessScore: 742,
  readinessDelta: 38,
  openGaps: 33,
  highGaps: 12,
  pendingEvidence: 18,
  overdueEvidence: 6,
  daysToReview: 14,
  reviewQuarter: "Q2 2026",
};

// ─── WORKFLOW ────────────────────────────────────────────────────
export const workflowCounts: WorkflowCounts = {
  assigned: 18,
  inReview: 13,
  approved: 8,
  evidenced: 34,
  overdue: 6,
  total: 79,
};

// ─── CONTROLS ────────────────────────────────────────────────────
export const controls: Control[] = [
  {
    id: "ctrl-001",
    name: "Access Control Review",
    domain: "IT Security · IAM Policy",
    risk: "high",
    evidenceStatus: "missing",
    workflowStatus: "overdue",
    owner: { initials: "IS", name: "IT Security Team", colorClass: "bg-[rgba(239,68,68,0.2)] text-risk-high" },
    deadline: "Mar 31, 2026",
    deadlineStatus: "overdue",
    description:
      "Periodic review of all IAM policies and user access rights to enforce least-privilege across banking systems and Azure resources. Required under SAMA CCSF Section 4.2.1.",
    samaRef: "SAMA CCSF 4.2.1",
  },
  {
    id: "ctrl-002",
    name: "Data Governance Framework",
    domain: "Data Governance · Compliance",
    risk: "high",
    evidenceStatus: "pending",
    workflowStatus: "in_review",
    owner: { initials: "DG", name: "Data Team", colorClass: "bg-[rgba(97,59,254,0.2)] text-[#A48DFF]" },
    deadline: "May 16, 2026",
    deadlineStatus: "soon",
    description:
      "Comprehensive data governance framework covering classification, lineage, ownership, and handling policies for all banking data assets aligned with SAMA data governance requirements.",
    samaRef: "SAMA DGF 2.1",
  },
  {
    id: "ctrl-003",
    name: "Encryption Standards Validation",
    domain: "Network Security · Cryptography",
    risk: "high",
    evidenceStatus: "review",
    workflowStatus: "in_review",
    owner: { initials: "NS", name: "Net Security", colorClass: "bg-[rgba(24,84,232,0.2)] text-[#6B9FFF]" },
    deadline: "May 19, 2026",
    deadlineStatus: "soon",
    description:
      "Validation of encryption standards across all data at-rest and in-transit scenarios. Covers AES-256 compliance, TLS 1.3 enforcement, and key management per SAMA CCSF.",
    samaRef: "SAMA CCSF 3.5",
  },
  {
    id: "ctrl-004",
    name: "Data Retention Policy",
    domain: "Compliance · SAMA Alignment",
    risk: "medium",
    evidenceStatus: "pending",
    workflowStatus: "assigned",
    owner: { initials: "CO", name: "Compliance Team", colorClass: "bg-[rgba(249,169,49,0.2)] text-risk-medium" },
    deadline: "May 24, 2026",
    deadlineStatus: "ok",
    description:
      "Formal data retention policy aligned with SAMA's data lifecycle management requirements. Covers retention periods, archival procedures, and secure disposal of expired financial data.",
    samaRef: "SAMA DLP 1.3",
  },
  {
    id: "ctrl-005",
    name: "Business Continuity & Resiliency",
    domain: "Infrastructure · DR Planning",
    risk: "medium",
    evidenceStatus: "approved",
    workflowStatus: "evidenced",
    owner: { initials: "IN", name: "Infrastructure", colorClass: "bg-[rgba(34,197,94,0.2)] text-risk-low" },
    deadline: "Jun 2, 2026",
    deadlineStatus: "ok",
    description:
      "Business continuity plan and disaster recovery procedures including RTO/RPO targets, failover testing results, and infrastructure resiliency validation per SAMA BCM framework.",
    samaRef: "SAMA BCM 2.0",
  },
  {
    id: "ctrl-006",
    name: "Audit Logging Standards",
    domain: "Compliance · SAMA",
    risk: "low",
    evidenceStatus: "approved",
    workflowStatus: "evidenced",
    owner: { initials: "CO", name: "Compliance Team", colorClass: "bg-[rgba(34,197,94,0.2)] text-risk-low" },
    deadline: "Jun 10, 2026",
    deadlineStatus: "ok",
    description:
      "Comprehensive audit logging configuration covering system events, user actions, and API calls. Logs retained for 12 months and accessible for audit review per SAMA requirements.",
    samaRef: "SAMA CCSF 4.4",
  },
  {
    id: "ctrl-007",
    name: "Privileged Access Management",
    domain: "IT Security · PAM",
    risk: "high",
    evidenceStatus: "pending",
    workflowStatus: "assigned",
    owner: { initials: "IS", name: "IT Security Team", colorClass: "bg-[rgba(239,68,68,0.2)] text-risk-high" },
    deadline: "May 28, 2026",
    deadlineStatus: "soon",
    description:
      "Implementation and validation of PAM controls for administrative accounts including session monitoring, just-in-time access provisioning, and privileged session recording.",
    samaRef: "SAMA PAM 1.1",
  },
  {
    id: "ctrl-008",
    name: "Third-Party Risk Assessment",
    domain: "Risk Management · Vendor",
    risk: "medium",
    evidenceStatus: "pending",
    workflowStatus: "assigned",
    owner: { initials: "RM", name: "Risk Management", colorClass: "bg-[rgba(249,169,49,0.2)] text-risk-medium" },
    deadline: "Jun 5, 2026",
    deadlineStatus: "ok",
    description:
      "Annual risk assessment of all third-party vendors with access to banking systems and customer data, covering due diligence, contract compliance, and security posture evaluation.",
    samaRef: "SAMA TPRM 3.0",
  },
  {
    id: "ctrl-009",
    name: "Network Segmentation Review",
    domain: "Network Security · Architecture",
    risk: "medium",
    evidenceStatus: "review",
    workflowStatus: "in_review",
    owner: { initials: "NS", name: "Net Security", colorClass: "bg-[rgba(24,84,232,0.2)] text-[#6B9FFF]" },
    deadline: "Jun 8, 2026",
    deadlineStatus: "ok",
    description:
      "Review of network segmentation controls to ensure proper isolation between core banking systems, DMZ, and internet-facing services in compliance with SAMA security architecture standards.",
  },
  {
    id: "ctrl-010",
    name: "Incident Response Procedures",
    domain: "Security Operations · IR",
    risk: "low",
    evidenceStatus: "approved",
    workflowStatus: "evidenced",
    owner: { initials: "SO", name: "SecOps Team", colorClass: "bg-[rgba(34,197,94,0.2)] text-risk-low" },
    deadline: "Jun 15, 2026",
    deadlineStatus: "ok",
    description:
      "Updated incident response procedures including the new 72-hour SAMA reporting obligation, escalation paths, stakeholder communication templates, and post-incident review process.",
    samaRef: "SAMA IR 2.1",
  },
];

// ─── EVIDENCE ────────────────────────────────────────────────────
export const evidenceItems: EvidenceItem[] = [
  {
    id: "ev-001",
    fileName: "IAM_Policy_Review_Q1_2026.pdf",
    controlId: "ctrl-001",
    controlName: "Access Control Review",
    stage: "review",
    submittedBy: { initials: "IS", name: "IT Security Team", colorClass: "bg-[rgba(239,68,68,0.2)] text-risk-high" },
    date: "May 8, 2026",
    fileSize: "2.4 MB",
    fileType: "PDF",
  },
  {
    id: "ev-002",
    fileName: "Data_Gov_Framework_v3.2.docx",
    controlId: "ctrl-002",
    controlName: "Data Governance Framework",
    stage: "pending",
    submittedBy: { initials: "DG", name: "Data Team", colorClass: "bg-[rgba(97,59,254,0.2)] text-[#A48DFF]" },
    date: "May 10, 2026",
    fileSize: "1.1 MB",
    fileType: "DOCX",
  },
  {
    id: "ev-003",
    fileName: "Encryption_Standards_Audit_Report.pdf",
    controlId: "ctrl-003",
    controlName: "Encryption Standards Validation",
    stage: "approved",
    submittedBy: { initials: "NS", name: "Net Security", colorClass: "bg-[rgba(24,84,232,0.2)] text-[#6B9FFF]" },
    date: "May 4, 2026",
    fileSize: "5.8 MB",
    fileType: "PDF",
  },
  {
    id: "ev-004",
    fileName: "BCP_DR_Test_Results_2026.xlsx",
    controlId: "ctrl-005",
    controlName: "Business Continuity & Resiliency",
    stage: "approved",
    submittedBy: { initials: "IN", name: "Infrastructure", colorClass: "bg-[rgba(34,197,94,0.2)] text-risk-low" },
    date: "Apr 28, 2026",
    fileSize: "890 KB",
    fileType: "XLSX",
  },
  {
    id: "ev-005",
    fileName: "Audit_Logging_Compliance_Check.json",
    controlId: "ctrl-006",
    controlName: "Audit Logging Standards",
    stage: "approved",
    submittedBy: { initials: "CO", name: "Compliance Team", colorClass: "bg-[rgba(34,197,94,0.2)] text-risk-low" },
    date: "Apr 20, 2026",
    fileSize: "320 KB",
    fileType: "JSON",
  },
  {
    id: "ev-006",
    fileName: "PAM_Implementation_Evidence.pdf",
    controlId: "ctrl-007",
    controlName: "Privileged Access Management",
    stage: "pending",
    submittedBy: { initials: "IS", name: "IT Security Team", colorClass: "bg-[rgba(239,68,68,0.2)] text-risk-high" },
    date: "May 11, 2026",
    fileSize: "3.1 MB",
    fileType: "PDF",
  },
  {
    id: "ev-007",
    fileName: "Network_Segmentation_Architecture.pdf",
    controlId: "ctrl-009",
    controlName: "Network Segmentation Review",
    stage: "review",
    submittedBy: { initials: "NS", name: "Net Security", colorClass: "bg-[rgba(24,84,232,0.2)] text-[#6B9FFF]" },
    date: "May 9, 2026",
    fileSize: "4.2 MB",
    fileType: "PDF",
  },
  {
    id: "ev-008",
    fileName: "IR_Procedures_Updated_2026.docx",
    controlId: "ctrl-010",
    controlName: "Incident Response Procedures",
    stage: "approved",
    submittedBy: { initials: "SO", name: "SecOps Team", colorClass: "bg-[rgba(34,197,94,0.2)] text-risk-low" },
    date: "Apr 15, 2026",
    fileSize: "780 KB",
    fileType: "DOCX",
  },
];

// ─── SAMA UPDATES ────────────────────────────────────────────────
export const samaUpdates: SamaUpdate[] = [
  {
    id: "sama-001",
    title: "Cloud Security Controls Update — SAMA CCSF 2.1",
    description:
      "Updated requirements for cloud data residency, access control segregation, and encryption key management for banking systems hosted on cloud platforms.",
    date: "May 6, 2026",
    type: "New Circular",
    status: "detected",
    impactedControls: 5,
    isNew: true,
  },
  {
    id: "sama-002",
    title: "Third-Party Risk Management Framework Update",
    description:
      "Enhanced due diligence requirements for all third-party vendors with access to banking systems or customer data, including annual re-assessment obligations.",
    date: "May 2, 2026",
    type: "Amendment",
    status: "detected",
    impactedControls: 4,
    isNew: true,
  },
  {
    id: "sama-003",
    title: "Cybersecurity Framework — Incident Reporting Revision",
    description:
      "New 72-hour mandatory incident reporting obligation for critical IT system events with structured SAMA notification procedures and escalation requirements.",
    date: "Apr 22, 2026",
    type: "Amendment",
    status: "mapped",
    impactedControls: 3,
  },
  {
    id: "sama-004",
    title: "Privileged Access Management Guidelines",
    description:
      "Mandatory PAM controls for administrative accounts including session monitoring, just-in-time provisioning, and privileged session recording requirements.",
    date: "Apr 14, 2026",
    type: "Guideline",
    status: "mapped",
    impactedControls: 6,
  },
  {
    id: "sama-005",
    title: "Open Banking API Standards — Data Governance",
    description:
      "Compliance framework for open banking APIs covering consent management, data portability, and audit logging requirements for API-exposed banking services.",
    date: "Apr 10, 2026",
    type: "Circular Update",
    status: "assigned",
    impactedControls: 7,
  },
  {
    id: "sama-006",
    title: "Financial Data Classification Policy",
    description:
      "Classification framework for financial customer data with tiered handling, storage, and transfer requirements based on sensitivity and regulatory exposure.",
    date: "Mar 28, 2026",
    type: "Policy",
    status: "assigned",
    impactedControls: 5,
  },
];

// ─── TASKS ────────────────────────────────────────────────────────
export const myTasks: Task[] = [
  {
    id: "task-001",
    title: "Review Access Control evidence submitted by IT Security",
    meta: "Evidence Validation · IT Security Team",
    priority: "high",
    due: "Overdue",
    deadlineStatus: "overdue",
  },
  {
    id: "task-002",
    title: "Approve Data Governance Framework document v3.2",
    meta: "Approval Required · Data Team",
    priority: "high",
    due: "4 days",
    deadlineStatus: "soon",
  },
  {
    id: "task-003",
    title: "Map new SAMA CCSF 2.1 circular to impacted controls",
    meta: "Regulatory Mapping · SAMA Update",
    priority: "medium",
    due: "7 days",
    deadlineStatus: "soon",
  },
  {
    id: "task-004",
    title: "Confirm audit evidence export scope for Q2 review",
    meta: "Audit Pack · Q2 External Audit",
    priority: "low",
    due: "14 days",
    deadlineStatus: "ok",
  },
];

// ─── KANBAN BOARD ITEMS ─────────────────────────────────────────
export const boardItems: BoardItem[] = [
  // ── OVERDUE ──
  {
    id: "b-ov-1",
    name: "Access Control Review",
    domain: "IT Security · IAM",
    risk: "high",
    owner: { initials: "IS", name: "IT Security", colorClass: "bg-[rgba(239,68,68,0.2)] text-risk-high" },
    deadline: "Mar 31, 2026",
    deadlineStatus: "overdue",
    workflowStatus: "overdue",
    samaRef: "CCSF 4.2.1",
  },
  {
    id: "b-ov-2",
    name: "Password Policy Enforcement",
    domain: "IT Security · IAM",
    risk: "high",
    owner: { initials: "IS", name: "IT Security", colorClass: "bg-[rgba(239,68,68,0.2)] text-risk-high" },
    deadline: "Apr 15, 2026",
    deadlineStatus: "overdue",
    workflowStatus: "overdue",
    samaRef: "CCSF 4.1",
  },
  {
    id: "b-ov-3",
    name: "Vendor Security Assessment",
    domain: "Risk Mgmt · Vendor",
    risk: "medium",
    owner: { initials: "RM", name: "Risk Mgmt", colorClass: "bg-[rgba(249,169,49,0.2)] text-risk-medium" },
    deadline: "Apr 30, 2026",
    deadlineStatus: "overdue",
    workflowStatus: "overdue",
    samaRef: "TPRM 3.0",
  },
  // ── ASSIGNED ──
  {
    id: "b-as-1",
    name: "Data Retention Policy",
    domain: "Compliance · SAMA",
    risk: "medium",
    owner: { initials: "CO", name: "Compliance", colorClass: "bg-[rgba(249,169,49,0.2)] text-risk-medium" },
    deadline: "May 24, 2026",
    deadlineStatus: "soon",
    workflowStatus: "assigned",
    samaRef: "DLP 1.3",
  },
  {
    id: "b-as-2",
    name: "Privileged Access Management",
    domain: "IT Security · PAM",
    risk: "high",
    owner: { initials: "IS", name: "IT Security", colorClass: "bg-[rgba(239,68,68,0.2)] text-risk-high" },
    deadline: "May 28, 2026",
    deadlineStatus: "soon",
    workflowStatus: "assigned",
    samaRef: "PAM 1.1",
  },
  {
    id: "b-as-3",
    name: "Third-Party Risk Assessment",
    domain: "Risk Mgmt · Vendor",
    risk: "medium",
    owner: { initials: "RM", name: "Risk Mgmt", colorClass: "bg-[rgba(249,169,49,0.2)] text-risk-medium" },
    deadline: "Jun 5, 2026",
    deadlineStatus: "ok",
    workflowStatus: "assigned",
    samaRef: "TPRM 3.0",
  },
  {
    id: "b-as-4",
    name: "Cloud Security Baseline",
    domain: "IT Security · Cloud",
    risk: "high",
    owner: { initials: "IS", name: "IT Security", colorClass: "bg-[rgba(239,68,68,0.2)] text-risk-high" },
    deadline: "Jun 1, 2026",
    deadlineStatus: "ok",
    workflowStatus: "assigned",
    samaRef: "CCSF 2.1",
  },
  {
    id: "b-as-5",
    name: "API Security Review",
    domain: "Network · Open Banking",
    risk: "medium",
    owner: { initials: "NS", name: "Net Security", colorClass: "bg-[rgba(24,84,232,0.2)] text-[#6B9FFF]" },
    deadline: "Jun 7, 2026",
    deadlineStatus: "ok",
    workflowStatus: "assigned",
  },
  // ── IN REVIEW ──
  {
    id: "b-ir-1",
    name: "Data Governance Framework",
    domain: "Data Governance",
    risk: "high",
    owner: { initials: "DG", name: "Data Team", colorClass: "bg-[rgba(97,59,254,0.2)] text-[#A48DFF]" },
    deadline: "May 16, 2026",
    deadlineStatus: "soon",
    workflowStatus: "in_review",
    samaRef: "DGF 2.1",
  },
  {
    id: "b-ir-2",
    name: "Encryption Standards Validation",
    domain: "Network · Cryptography",
    risk: "high",
    owner: { initials: "NS", name: "Net Security", colorClass: "bg-[rgba(24,84,232,0.2)] text-[#6B9FFF]" },
    deadline: "May 19, 2026",
    deadlineStatus: "soon",
    workflowStatus: "in_review",
    samaRef: "CCSF 3.5",
  },
  {
    id: "b-ir-3",
    name: "Network Segmentation Review",
    domain: "Network · Architecture",
    risk: "medium",
    owner: { initials: "NS", name: "Net Security", colorClass: "bg-[rgba(24,84,232,0.2)] text-[#6B9FFF]" },
    deadline: "Jun 8, 2026",
    deadlineStatus: "ok",
    workflowStatus: "in_review",
  },
  {
    id: "b-ir-4",
    name: "User Authentication Controls",
    domain: "IT Security · MFA",
    risk: "high",
    owner: { initials: "IS", name: "IT Security", colorClass: "bg-[rgba(239,68,68,0.2)] text-risk-high" },
    deadline: "May 22, 2026",
    deadlineStatus: "soon",
    workflowStatus: "in_review",
    samaRef: "CCSF 4.3",
  },
  // ── APPROVED ──
  {
    id: "b-ap-1",
    name: "Audit Logging Standards",
    domain: "Compliance · SAMA",
    risk: "low",
    owner: { initials: "CO", name: "Compliance", colorClass: "bg-[rgba(34,197,94,0.2)] text-risk-low" },
    deadline: "Jun 10, 2026",
    deadlineStatus: "ok",
    workflowStatus: "approved",
    samaRef: "CCSF 4.4",
  },
  {
    id: "b-ap-2",
    name: "Incident Response Procedures",
    domain: "SecOps · IR",
    risk: "low",
    owner: { initials: "SO", name: "SecOps", colorClass: "bg-[rgba(34,197,94,0.2)] text-risk-low" },
    deadline: "Jun 15, 2026",
    deadlineStatus: "ok",
    workflowStatus: "approved",
    samaRef: "IR 2.1",
  },
  {
    id: "b-ap-3",
    name: "Vulnerability Scanning Policy",
    domain: "IT Security · VAPT",
    risk: "medium",
    owner: { initials: "IS", name: "IT Security", colorClass: "bg-[rgba(239,68,68,0.2)] text-risk-high" },
    deadline: "Jun 12, 2026",
    deadlineStatus: "ok",
    workflowStatus: "approved",
    samaRef: "CCSF 5.1",
  },
  // ── EVIDENCED ──
  {
    id: "b-ev-1",
    name: "Business Continuity & Resiliency",
    domain: "Infrastructure · DR",
    risk: "medium",
    owner: { initials: "IN", name: "Infrastructure", colorClass: "bg-[rgba(34,197,94,0.2)] text-risk-low" },
    deadline: "Jun 2, 2026",
    deadlineStatus: "ok",
    workflowStatus: "evidenced",
    samaRef: "BCM 2.0",
  },
  {
    id: "b-ev-2",
    name: "Change Management Process",
    domain: "IT Operations · ITSM",
    risk: "low",
    owner: { initials: "IO", name: "IT Ops", colorClass: "bg-[rgba(97,59,254,0.2)] text-[#A48DFF]" },
    deadline: "Jun 18, 2026",
    deadlineStatus: "ok",
    workflowStatus: "evidenced",
  },
  {
    id: "b-ev-3",
    name: "Asset Inventory Management",
    domain: "IT Operations · CMDB",
    risk: "low",
    owner: { initials: "IO", name: "IT Ops", colorClass: "bg-[rgba(97,59,254,0.2)] text-[#A48DFF]" },
    deadline: "Jun 20, 2026",
    deadlineStatus: "ok",
    workflowStatus: "evidenced",
  },
  {
    id: "b-ev-4",
    name: "System Backup Procedures",
    domain: "Infrastructure · Recovery",
    risk: "low",
    owner: { initials: "IN", name: "Infrastructure", colorClass: "bg-[rgba(34,197,94,0.2)] text-risk-low" },
    deadline: "Jun 22, 2026",
    deadlineStatus: "ok",
    workflowStatus: "evidenced",
    samaRef: "BCM 1.2",
  },
  {
    id: "b-ev-5",
    name: "Security Awareness Training",
    domain: "HR · People Security",
    risk: "low",
    owner: { initials: "HR", name: "HR Dept", colorClass: "bg-[rgba(97,59,254,0.2)] text-[#A48DFF]" },
    deadline: "Jun 25, 2026",
    deadlineStatus: "ok",
    workflowStatus: "evidenced",
  },
];

// ─── NOTIFICATIONS ──────────────────────────────────────────────
export const notifications: Notification[] = [
  // Unread — high priority
  {
    id: "notif-001",
    type: "sama",
    title: "New SAMA Circular Detected",
    description: "Cloud Security Controls Update (SAMA CCSF 2.1) has been published. 5 controls in your register are potentially impacted and require immediate mapping.",
    timestamp: "2026-05-13T08:14:00",
    timeAgo: "2 hours ago",
    read: false,
    priority: "high",
    actionLabel: "Map Controls",
    actionHref: "/regulations",
    meta: "SAMA CCSF 2.1 · New Circular",
  },
  {
    id: "notif-002",
    type: "sama",
    title: "Third-Party Risk Framework Amendment",
    description: "SAMA has amended the Third-Party Risk Management Framework, introducing enhanced due diligence requirements for all vendors with access to banking systems.",
    timestamp: "2026-05-12T16:45:00",
    timeAgo: "17 hours ago",
    read: false,
    priority: "high",
    actionLabel: "Review Update",
    actionHref: "/regulations",
    meta: "SAMA TPRM · Amendment",
  },
  {
    id: "notif-003",
    type: "evidence",
    title: "Evidence Overdue — Access Control Review",
    description: "IAM Policy Review evidence for ctrl-001 was due on Mar 31, 2026 and has not been submitted. This control is now flagged as overdue in your governance board.",
    timestamp: "2026-05-13T07:00:00",
    timeAgo: "3 hours ago",
    read: false,
    priority: "high",
    actionLabel: "View Control",
    actionHref: "/controls",
    meta: "ctrl-001 · IT Security · Overdue",
  },
  {
    id: "notif-004",
    type: "approval",
    title: "Evidence Awaiting Your Approval",
    description: "IAM Policy Review Q1 2026 (PDF, 2.4 MB) has been submitted by IT Security Team and is pending your review and approval before it can be marked as evidenced.",
    timestamp: "2026-05-12T14:22:00",
    timeAgo: "19 hours ago",
    read: false,
    priority: "medium",
    actionLabel: "Review & Approve",
    actionHref: "/governance",
    meta: "IT Security Team · Evidence Approval",
  },
  {
    id: "notif-005",
    type: "task",
    title: "Task Assigned — SAMA Circular Mapping",
    description: "You have been assigned to map the new SAMA CCSF 2.1 circular to impacted controls in the register. Target completion: May 20, 2026.",
    timestamp: "2026-05-13T08:30:00",
    timeAgo: "1 hour ago",
    read: false,
    priority: "medium",
    actionLabel: "Start Task",
    actionHref: "/governance",
    meta: "Assigned by · Compliance Team",
  },
  // Read notifications
  {
    id: "notif-006",
    type: "approval",
    title: "Evidence Approved — Audit Logging Standards",
    description: "Logging Compliance Check v2 submitted by the Compliance Team has been approved. Control ctrl-006 is now marked as Evidenced in the governance board.",
    timestamp: "2026-05-11T11:05:00",
    timeAgo: "2 days ago",
    read: true,
    priority: "low",
    actionLabel: "View Control",
    actionHref: "/controls",
    meta: "ctrl-006 · Compliance Team",
  },
  {
    id: "notif-007",
    type: "evidence",
    title: "Evidence Submitted for Review",
    description: "Data Governance Framework v3.2 (DOCX, 1.1 MB) has been submitted by the Data Team for review. Please review and approve within 5 business days.",
    timestamp: "2026-05-10T09:30:00",
    timeAgo: "3 days ago",
    read: true,
    priority: "medium",
    actionLabel: "View Evidence",
    actionHref: "/evidence",
    meta: "Data Team · ctrl-002",
  },
  {
    id: "notif-008",
    type: "system",
    title: "Readiness Score Improved",
    description: "Your governance readiness score has increased by +38 points to 742/1000 following the approval of three new evidence items. Keep up the momentum.",
    timestamp: "2026-05-09T17:00:00",
    timeAgo: "4 days ago",
    read: true,
    priority: "low",
    actionLabel: "View Dashboard",
    actionHref: "/dashboard",
    meta: "Score: 742 / 1000 · +38 this period",
  },
  {
    id: "notif-009",
    type: "task",
    title: "Task Completed — Incident Response Procedures",
    description: "The Incident Response Procedures evidence has been submitted, reviewed, and approved. ctrl-010 is now fully evidenced ahead of the Q2 2026 audit cycle.",
    timestamp: "2026-05-08T15:20:00",
    timeAgo: "5 days ago",
    read: true,
    priority: "low",
    actionHref: "/controls",
    meta: "SecOps Team · ctrl-010",
  },
  {
    id: "notif-010",
    type: "system",
    title: "Q2 2026 Audit Cycle — 14 Days Remaining",
    description: "The Q2 2026 external audit review is scheduled in 14 days. You currently have 18 pending evidence items and 6 overdue controls. Prioritise your action list.",
    timestamp: "2026-05-07T08:00:00",
    timeAgo: "6 days ago",
    read: true,
    priority: "medium",
    actionLabel: "View Dashboard",
    actionHref: "/dashboard",
    meta: "Q2 2026 · External Audit",
  },
];

export const approvalQueue: Task[] = [
  {
    id: "apq-001",
    title: "Encryption_Audit_2026.pdf submitted by Net Sec",
    meta: "Evidence Approval · Encryption Standards",
    priority: "medium",
    due: "Pending",
    deadlineStatus: "soon",
  },
  {
    id: "apq-002",
    title: "IAM Policy Review Q1 submitted by IT Security",
    meta: "Evidence Approval · Access Control",
    priority: "high",
    due: "Pending",
    deadlineStatus: "soon",
  },
  {
    id: "apq-003",
    title: "Logging Compliance Check v2 approved by Compliance",
    meta: "Final Approval · Audit Logging",
    priority: "low",
    due: "Done",
    deadlineStatus: "ok",
  },
];
